### ISSUE TITLE
Needs access to XDG_DOWNLOAD_DIR

### ISSUE THREAD

**Issue by x80486** [flathub/io.freetubeapp.FreeTube#1]
The application can download stuff, so it needs access to `XDG_DOWNLOAD_DIR` in order to persist the downloads.

**Comment by mat8913** [comment]
I'll add this because some people might find it useful, but please note that upstream does not currently consider the download button to be a proper feature yet: https://github.com/FreeTubeApp/FreeTube/issues/150#issuecomment-411768019
