### ISSUE TITLE
0.8.0 is released.

### ISSUE THREAD

**Issue by gitcontrib0** [flathub/io.freetubeapp.FreeTube#32]
Please update the flatpak to v0.8.0. It is a major release that is a full rewrite of the app and includes various stability improvements due to the invidious shutdown.

0.8.0 blog post: https://freetube.writeas.com/release-0-8-0-beta-the-rewrite-is-here

**Comment by ovari** [comment]
Bump version number to v0.9.0
https://github.com/FreeTubeApp/FreeTube/commit/1e1d0164f0590ed9a5db821f67df247b87b7bfd6

**Comment by PrestonN** [comment]
I don't know if @mat8913 is available to try and help out with this, as I'm not familiar with how to bundle for Flatpak and need to research it a bit more.

Last I know he's still blocked by #27 but I haven't heard from anyone in a while.  I'm aware that this is a popular option and I want to make it available.  I'll look at it as soon as I can.

**Comment by mat8913** [comment]
Sorry, I've been pretty busy with work lately. I think what I'm going to have to do is bundle the pre-built .zip files, since I was unable to get it to build in flatpak-builder.

I am a little worried about the backwards compatibility. Since flatpaks update automatically on most systems, I don't want anyone to suddenly lose their subscriptions.

**Comment by PrestonN** [comment]
I made sure to make everyone aware that they'll be losing their subscriptions when they upgrade.  The data won't technically be deleted during the upgrade as well.

I can maybe add a button to check for subscriptions from the previous version and import if that would be acceptable.

**Comment by PrestonN** [comment]
Should be available now in the latest dev build.  This will be included with v0.9.0.  Users should be able to use this in order to restore their previous subscriptions.

**Comment by ovari** [comment]
> Should be available now in the latest dev build. This will be included with v0.9.0. Users should be able to use this in order to restore their previous subscriptions.

The latest version showing at https://github.com/FreeTubeApp/FreeTube/tags is v0.8.0-beta. Can you please provide a link? Thank you

**Comment by PrestonN** [comment]
As I said, the ability to check for old FreeTube subscriptions are in the _dev_ builds, as in they're not completely released yet.  Dev builds are automatically created via [GitHub Actions](https://github.com/FreeTubeApp/FreeTube/actions?query=workflow%3ABuild).

This change also has nothing to do with building for Flatpak.  It was more so to help out with the concern that @mat8913 brought up.
