### ISSUE TITLE
Error when trying to watch videos

### ISSUE THREAD

**Issue by gdurif** [flathub/io.freetubeapp.FreeTube#55]
Hi,
I am not sure where to report this, whether it is a FlatPak FreeTube app related issue or general FreeTube related issue.

When trying to watch some videos (like fH14oI_PJAQ), I get the following errors:
```
Local API ERROR: Error: Status code: 404
Falling back to Invidious API
```
and then 
```
Invidious API ERROR: {"error":"Could not extract video info. Instance is likely blocked."}
```
The video eventually fails to load and I get this empty player:

![image](https://user-images.githubusercontent.com/38720408/123279382-513e9a80-d4f7-11eb-8a1a-5d3f9f0b6cef.png)

I mention that I am using the latest version of FreeTube available on FlatHub. A few videos are working but not many.
Thanks in advance

**Comment by PrestonN** [comment]
Hey there. Apologies for not seeing this.

We track issues over in [this](https://github.com/FreeTubeApp/FreeTube) repository for all builds. It's more likely to be seen when created over here. This repository is only for the config files needed for FreeTube to be published on Flathub.

As for your issue, we published a new release today (Should be on Flathub very soon after I post this), let me know if the new release helps.

Thanks!

**Comment by gdurif** [comment]
Thanks for the reply and sorry for posting at the wrong place. I got the update and every thing seems to be working. Thanks for your great work.
