### ISSUE TITLE
There was an error calling the Invidious API

### ISSUE THREAD

**Issue by VaGNaroK** [flathub/io.freetubeapp.FreeTube#6]
I'm having the right error when I import my youtube subscriptions via file. I'm using the flatpak version of the official flathub repository.

https://postimg.cc/YjqwCQTn

Any idea?

I'm having the right error when I import my youtube subscriptions via file. I'm using the flatpak version of the official flathub repository.

https://postimg.cc/YjqwCQTn

Any idea?

My system:

System:
  Host: vagnarok-PC Kernel: 4.18.0-16-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.0.10 Distro: Linux Mint 19.1 Tessa 
Machine:
  Type: Desktop System: Itautec S.A. product: Infoway v: Corp 
  serial: <root required> 
  Mobo: Itautec S.A. model: ST 4262 v: ST-4262 Padrao 06(Itautec_M) 
  serial: <root required> BIOS: Itautec ST 4262 6.00 PG -SL2.1 v: FC 
  date: 08/21/2009 
CPU:
  Topology: Dual Core model: Intel Core2 Duo E8400 bits: 64 type: MCP 
  L2 cache: 6144 KiB 
  Speed: 2826 MHz min/max: 2000/2667 MHz Core speeds (MHz): 1: 2826 2: 2826 
Graphics:
  Device-1: NVIDIA G96 [GeForce 9500 GT] driver: nvidia v: 340.107 
  Display: x11 server: X.Org 1.20.1 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1400x900~60Hz 
  OpenGL: renderer: GeForce 9500 GT/PCIe/SSE2 v: 3.3.0 NVIDIA 340.107 
Audio:
  Device-1: Intel 82801JD/DO HD Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k4.18.0-16-generic 
Network:
  Device-1: Intel 82567LM-3 Gigabit Network driver: e1000e 
  IF: enp0s25 state: up speed: 100 Mbps duplex: full mac: 00:24:1d:f3:7a:35 
Drives:
  Local Storage: total: 2.28 TiB used: 1.20 TiB (52.4%) 
  ID-1: /dev/sda vendor: Western Digital model: WD5000AAKS-00D2B0 
  size: 465.76 GiB 
  ID-2: /dev/sdb vendor: Samsung model: HD204UI size: 1.82 TiB 
  ID-3: /dev/sdc type: USB vendor: SanDisk model: Cruzer Blade 
  size: 7.45 GiB 
Partition:
  ID-1: / size: 457.45 GiB used: 203.05 GiB (44.4%) fs: ext4 dev: /dev/sda1 
Sensors:
  System Temperatures: cpu: 48.0 C mobo: N/A gpu: nvidia temp: 52 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 221 Uptime: 26m Memory: 7.67 GiB used: 3.54 GiB (46.2%) 
  Shell: bash inxi: 3.0.27

**Comment by PrestonN** [comment]
Hey there.  It's likely that your subscription file has channels that have been terminated by YouTube.  If you know which channels, try removing them before you get your export file.  If not, could you please upload your subscriptions file either here or by emailing me at freetubeapp@protonmail.com and I can send you a cleaned up export file.

If you end up sending an export file, I will use it for testing so that I can prevent this in the future.

**Comment by mat8913** [comment]
I'm going to close this for now because it seems to be solved upstream. Feel free to reopen or make a new issue if the problem still exists.
