### ISSUE TITLE
Data Settings options only show Donwloads folder

### ISSUE THREAD

**Issue by sudonikgr** [flathub/io.freetubeapp.FreeTube#62]
I clicked 'Data Settings' - 'Import Subscriptions' to import a **.db** file, but I only see the _Home/Downloads_ folder. It is not possible to select other folders or disks. This does not happen in the appimage.
Edit: I tried all the other options in the Data Settings section and it's the same problem. For every button, only the Downloads folder shows and nothing else.

**Comment by PrestonN** [comment]
This is part of the Flatpak's sandboxing features to prevent applications from having total control across your machine. You can adjust these permissions using something like [Flatseal](https://www.flathub.org/apps/details/com.github.tchx84.Flatseal) to give FreeTube more access across your device.
