### ISSUE TITLE
Doesnt start on Wayland

### ISSUE THREAD

**Issue by firefoxlover** [flathub/io.freetubeapp.FreeTube#67]
I guess its not supported yet, but it would be great if we could use it on Wayland too.

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-28-generic (64-bit)
Graphics Platform: Wayland

**Comment by marshallishere** [comment]
The issue was closed and it seems to work now, there's any update on this issue?

**Comment by bbhtt** [comment]
> The issue was close and it seems to work now, there's any update on this issue?

Needs to be in a released version. The Electron version upgrade was merged on August 26 https://github.com/FreeTubeApp/FreeTube/commit/680abbebd81dbe746105c931523ed3082bc0302c 

The last release is from August 12 https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.17.1-beta

**Comment by marshallishere** [comment]
Oh, my bad. Thanks!

**Comment by mooreye** [comment]
How long before 0.17 release? This is a pretty bad issue that makes FreeTube unusable for me

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@firefoxlover is this fixed for u? If so please close the issue
