### ISSUE TITLE
Icon not showing up

### ISSUE THREAD

**Issue by mat8913** [flathub/io.freetubeapp.FreeTube#7]
In the screenshot provided in #6, the FreeTube icon isn't showing for some reason. On both my laptops (running GNOME) the icon does show, so further investigation is needed.

**Comment by diogogomes** [comment]
Confirmed using:

**FreeTube 0.5.3 Beta**
**Xubuntu 16.04**

---

**Note: This happens on AppImage version too.**

**Comment by mat8913** [comment]
I've pushed an update which I hope fixes this. Please try it and let me know.

**Comment by diogogomes** [comment]
@mat8913,

It **works** using:

**FreeTube 0.6.0 Beta (flatpak)**
**Xubuntu 16.04**

**Comment by mat8913** [comment]
Fixed by 7d504fbbdc2a34b21659c22952d83c3d852ba378

Thank you for testing

**Comment by mat8913** [comment]
@diogogomes 
Actually, one last thing if you have some time. Could you please also test if the AppImage version of 0.6.0 works? If it doesn't, I'll forward the patch upstream.

**Comment by diogogomes** [comment]
@mat8913 

The **desktop icon it's working** using AppImage but the **window icon/decoration is missing**.

**FreeTube 0.6.0 Beta (AppImage)**
**Xubuntu 16.04**

**Comment by mat8913** [comment]
Thanks again for testing. I've sent the patch upstream.
