### ISSUE TITLE
Black Screen Upon Launch

### ISSUE THREAD

**Issue by ljcoogan** [flathub/io.freetubeapp.FreeTube#73]
I'm trying to use the flatpak on Fedora 36, but every time it launches it gives me the following errors, and proceeds to launch a black screen with the heading 'Subscriptions - FreeTube'. My best guess is it's something to do with my using Wayland (w/ proprietary nVidia drivers), but I'm not sure how to go about making it work.

```
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 08:26:37.045: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:26:37.045: Failed to load module "pk-gtk-module"
Gtk-Message: 08:26:37.045: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:26:37.045: Failed to load module "pk-gtk-module"
[2:0803/082637.065679:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
TypeError: Cannot destructure property 'value' of 'object null' as it is null.
    at /app/freetube/resources/app.asar/dist/main.js:1:4801
    at async W (/app/freetube/resources/app.asar/dist/main.js:1:4757)
    at async App.<anonymous> (/app/freetube/resources/app.asar/dist/main.js:1:8870)
(node:2) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(Use `freetube --trace-warnings ...` to show where the warning was created)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

![image](https://user-images.githubusercontent.com/34213592/182562100-0219c9d5-8159-43d1-b1e6-d1f841661e75.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is an issue with Electron. We need to update our electron dependency to make this work on wayland. If possible try to start electron in xorg

**Comment by ljcoogan** [comment]
By start electron in xorg, do you mean start FreeTube with xorg? I just verified that I get the same error messages and blank window whether I start with '--socket=xorg' or '--socket=wayland'.

If you mean something else let me know and I can try it out for you

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
More info can be found in https://github.com/FreeTubeApp/FreeTube/issues/2269

https://github.com/FreeTubeApp/FreeTube/issues/2190

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I would recommend closing this on because it doesn't got anything to do with flatpak. 

Comment in one of the issues and someone will help u out.

**Comment by pm4rcin** [comment]
Check [that comment](https://github.com/FreeTubeApp/FreeTube/issues/2269#issuecomment-1214435828) and upvote if it works for you.

**Comment by ljcoogan** [comment]
> I would recommend closing this on because it doesn't got anything to do with flatpak.
> 
> Comment in one of the issues and someone will help u out.

Fair enough, thanks for your responses anyway
