### ISSUE TITLE
Stuttering playback when using video acceleration on XWayland

### ISSUE THREAD

**Issue by loveisfoss** [flathub/io.freetubeapp.FreeTube#85]
I decided lately to try using video acceleration with Freetube.

I have tried this in two devices running Fedora 37 (Gnome) and experienced exact the same behavior.

 * A laptop with an intel APU (Intel i7 1255U), using intel-media-driver.

* A desktop with an AMD Radeon GPU (RX 6700 XT). Using amdgpu driver and mesa-va-drivers-freeworld.

## In an X11 session
I managed to make video acceleration work (both with the flatpak and the rpm version of FreeTube) with the following command and everything worked fine.
`flatpak run io.freetubeapp.FreeTube --disable-features=UseChromeOSDirectVideoDecoder --use-gl=egl`

## In a Wayland session
Freetube defaults to using XWayland. I managed to make video acceleration work with the previous command but **the video playback is stuttering** when video acceleration is turned on.

## The catch
**When using the rpm provided at the FreeTube website, the above issue does not happen.** Video acceleration works on a Wayland session, by using XWayland, and the video is smooth and nice.

So, my question is: Could there exist some limitation when it comes to hardware acceleration when using Freetube in XWayland with flatpak?

Note: I managed to run FreeTube using Wayland (not XWayland) with the following command but was never able to make video acceleration work (neither with the flatpak nor with the rpm version).
`flatpak run --nosocket=x11 --socket=fallback-x11 --socket=wayland io.freetubeapp.FreeTube --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --disable-features=UseChromeOSDirectVideoDecoder --use-gl=egl`

Note2: I check if video acceleration is up and running by using the `intel_gpu_top` command. One can also get an indication about gpu usage with the `radeontop` command.

**Comment by JoshuaMacklin** [comment]
Hello loveisfoss, would love to see if my [PR](https://github.com/flathub/io.freetubeapp.FreeTube/pull/93#issuecomment-1773356053) fixed your issue on your end, its working for me :)

**Comment by loveisfoss** [comment]
Hey @JoshuaMacklin 

Thanks for this PR! FreeTube defaults to Wayland with it and video playback is smooth.
However, as I had mentioned in my issue report, video acceleration does not work when FreeTube runs on Wayland, even if the flags `--use-gl=egl --disable-features=UseChromeOSDirectVideoDecoder` are set.

**Comment by absidue** [comment]
@loveisfoss If video acceleration doesn't work in Chrome, it won't work in FreeTube either, as FreeTube use Electron which is built on top of Chromium.
