### ISSUE TITLE
Will switching to Electron Builder be a problem?

### ISSUE THREAD

**Issue by PrestonN** [flathub/io.freetubeapp.FreeTube#9]
Hey there @mat8913 

I've been recently having some issues with getting the extension to work with the latest version of Electron provided by electron-forge.  I'm only in the early stages of this, but I'm thinking about switching over to Electron Builder for future builds of FreeTube.  Will this cause a problem with the Flatpak release?  I see that Electron Builder doesn't support Flatpak but I'm not sure how the build process of it goes.  If needed, I can keep electron-forge as a dependency but I'd primarily use Electron Builder moving forward.  Curious on your thoughts with this.

**Comment by mat8913** [comment]
It should be fine, we're not using electron-forge to make the Flatpak. I notice that Electron Builder supports AppImage, so worst case scenario we could just convert the AppImage into a Flatpak ([example](https://github.com/flathub/com.beakerbrowser.Beaker/blob/00c36fd1b99b48afdbdc95fd5a75d1c9bb2f00f1/com.beakerbrowser.Beaker.yml#L29)).

**Comment by PrestonN** [comment]
Great!  That's good to hear.  I wanted to make sure before I did any radical changes.  Thanks a bunch for maintaining this, it's very appreciated!

**Comment by TingPing** [comment]
>  I notice that Electron Builder supports AppImage, so worst case scenario we could just convert the AppImage into a Flatpak

Thats a bad hack... AppImages are built against host libraries not guarenteed to work in Flatpak.
