### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by qoijjj** [flathub/io.freetubeapp.FreeTube#96]
Getting verification would allow an increased level of user trust.

https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714
https://flathub.org/apps/collection/verified/1

I believe this would require the blessing of upstream devs via hosting a file.

**Comment by PrestonN** [comment]
I've gone ahead and went through the steps to get FreeTube verified on Flathub. You should start to see the badge on the site very soon.
