### ISSUE TITLE
source of updates

### ISSUE THREAD

**Issue by lexay** [flathub/io.freetubeapp.FreeTube#97]
Hi!

I've received an update for FreeTube today, but there seems no changes were made recently on any of the branches...
Is there a weird thing going on with flathub?

How do I check what's changed on my side?

![freetube_updates](https://github.com/flathub/io.freetubeapp.FreeTube/assets/77849004/e1d2b4a0-fbda-4138-9650-8f0f8760558a)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It could be because of this https://github.com/flathub/io.freetubeapp.FreeTube/issues/96#issuecomment-1915190123

**Comment by bbhtt** [comment]
That should not cause an update. It's likely an old update or something. Can you show the output of `flatpak info io.freetubeapp.FreeTube` ?

The last official build that was published happened 4 months ago https://buildbot.flathub.org/#/apps/io.freetubeapp.FreeTube

**Comment by lexay** [comment]
> That should not cause an update. It's likely an old update or something. Can you show the output of `flatpak info io.freetubeapp.FreeTube` ?
> 
> The last official build that was published happened 4 months ago https://buildbot.flathub.org/#/apps/io.freetubeapp.FreeTube

I checked before removing and after installing FT again. Output is identical.

![freetube_updates_info](https://github.com/flathub/io.freetubeapp.FreeTube/assets/77849004/d701c10d-4131-455b-ad1d-850819276bc0)

**Comment by bbhtt** [comment]
Yes so the commit and date will tell you exactly when the last update happened. You are running this commit https://github.com/flathub/io.freetubeapp.FreeTube/commit/b6bf189bfb2e1a466d53bceccbf13c3968856f31 shortened as b6bf189b from 2023-10-10

If an update happened both the date and the commits would change.

flatpak remote-info flathub io.freetubeapp.FreeTube will show you that, that commit is also the latest version available through Flathub:

```
flatpak remote-info flathub io.freetubeapp.FreeTube 

FreeTube - An Open Source YouTube app for privacy

        ID: io.freetubeapp.FreeTube
       Ref: app/io.freetubeapp.FreeTube/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 0.19.1 Beta
   License: AGPL-3.0+
Collection: org.flathub.Stable
  Download: 93.6 MB
 Installed: 236.4 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: d32482e7eeeaaf1a84884ccebf9de975309729925479d39cfd04a044071db3dc
    Parent: df186ea2219d0eeeac50f45f204adcad72cdea894ce45b53fa3d95c16d3670df
   Subject: Update freedesktop sdk to 23.08 (b6bf189b)
      Date: 2023-10-10 00:05:44 +0000
```

**Comment by lexay** [comment]
> `flatpak remote-info flathub io.freetubeapp.FreeTube` will show you that, that commit is also the latest version available through Flathub:

Yep, checked that too before removing. 

Maybe it was a flatpak plugin for `pamac` glitch idk.

**Comment by lexay** [comment]
Anyway it seems the issue was not on the remote.
Thank you fro your trouble!
